### ISSUE TITLE
[FEATURE] Child categories

### ISSUE THREAD

**Issue by BasToTheMax** [Paymenter/Paymenter#100]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Creating child categories. Example:
Category "minecraft" can have child categories with products: "bungeecord", "papermc" ect

**Describe alternatives you've considered**
- Create normal categories...

**Additional context**

**Comment by CorwinDev** [comment]
Hi, please for features refer to https://paymenter.hellonext.co
