### ISSUE TITLE
[FEATURE] Cannot Delete Only Admin Account On System

### ISSUE THREAD

**Issue by zachary435** [Paymenter/Paymenter#104]
So i tried and tested it if you delete your only admin account you cannot log back in obviously so however since I'm hosting with you guys I cant access command line so now I'm locked out until I can get back in

How to replicate

Delete all users including you own and boom you are stuffed

**Comment by zachary435** [comment]
> i guess you can just open a ticket and they might do it for you 😄

I did but if it because a popular thing they do there gonna want to avoid idiots doing it cough cough like me

**Comment by AstroSam2100** [comment]
Good idea to prevent main admin account deletion

**Comment by cloudrack-ca** [comment]
agreed on this its a +1 
but to fix this issue IF IT HAPPENS for time being
ssh back into the server with paymenter installed `cd /var/www/paymenter `
re run the command
`php artisan p:user:create`

create the new admin account and re-login back in with the newly created account via artisan
