### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by imLunaris** [Paymenter/Paymenter#105]
**CSS**
I have downloaded the panel and all but it looks weird, there is no css some how

**Expected behavior**
the panel look you guys have made

**Screenshots**
![image](https://user-images.githubusercontent.com/98109755/234896519-78bd86b5-2174-4c6f-8a0c-d0ce1ea0b58f.png)

**Comment by CorwinDev** [comment]
Hi,

Did you follow our documentation?

**Comment by imLunaris** [comment]
Hey,

Yes i have followed the documentation

**Comment by CorwinDev** [comment]
Hi,

Could you maybe your our discord? https://discord.gg/xB4UUT3XQg It’s easier to help you there!

**Comment by imLunaris** [comment]
sure! let me join
