### ISSUE TITLE
[FEATURE] Limited products per user

### ISSUE THREAD

**Issue by parker02311** [Paymenter/Paymenter#109]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to any problems

**Describe the solution you'd like**
It would be nice to see a way for free products to have a limit per user. For example: A user could receive one free bot host and no more

**Describe alternatives you've considered**
Possibly a manual review of orders before manually completing orders.

**Comment by CorwinDev** [comment]
Hi,

This feature has now been included in commit 5b223e56d03b7828268a62707755789f5eecd9d1
