### ISSUE TITLE
[BUG] Client gets charged even when resources are full on the server

### ISSUE THREAD

**Issue by BoredKevin** [Paymenter/Paymenter#124]
**Describe the bug**
When the resources on the pterodactyl node is full, and a client purchases a server, it won't create the server. But, it will still charge the client.

**To Reproduce**
1. Make sure the node doesn't have enough resources for a new server (Not enough ram)
2. Client buys a server
3. Server won't get created, client still gets charged

**Expected behavior**
Client doesn't get charged, but shown an error, that the server is full and the server could not be created.

**Screenshots**
![image](https://github.com/Paymenter/Paymenter/assets/107290249/32b58c01-b3b7-4854-b707-1eac1347cfcc)
![image](https://github.com/Paymenter/Paymenter/assets/107290249/139ee691-d683-4ce6-87bc-8ea046761b70)

**Specifications (please complete the following information):**
 - OS: Ubuntu Server 22.04 LTS
 - PHP Version: 8.1.21
 - Paymenter Version: v0.7.1 (Latest)

**Comment by CorwinDev** [comment]
That is indeed true, but paymenter awaits the payment before it creates the server. 
So there is (currently) no way of checking if the server has enough resources to create a server

**Comment by BoredKevin** [comment]
Is there a way to  check for the available resources on the node before it awaits for the payment?

Maybe by using the pterodactyl [node details API](https://dashflo.net/docs/api/pterodactyl/v1/#req_9c01cbbf259f4b1f8aa6ff3b51dadd0e)
Checking the resources client servers have used, and then comparing it to the node's resources before awaiting the payment.
