### ISSUE TITLE
[BUG] Error 500 API Endpoint (api/admin/v1/invoices)

### ISSUE THREAD

**Issue by Paquito86** [Paymenter/Paymenter#126]
**Describe the bug**
Error 500 when trying to access API Endpoint "api/admin/v1/invoices"

**To Reproduce**
1. Open any app that lets you make API Requests (in this case Insomnia REST Client) or just use CURL.
2. Add your Bearer Token
3. Make a GET request to /api/admin/v1/invoices

**Expected behavior**
You'll get a 500 Error

**Screenshots**
![image](https://github.com/Paymenter/Paymenter/assets/66384054/2f4a4d97-3e94-491b-93f9-5877a0a9b0f2)
![image](https://github.com/Paymenter/Paymenter/assets/66384054/6b413051-b42b-4a30-8990-9e3e3e2551c6)

**Comment by CorwinDev** [comment]
Hi this should be fixed in the commit 044777ffdb6d80c1a346a7e6709c3b0e7f12117c
This bug fix will rollout in the coming version
