### ISSUE TITLE
[BUG] Demo, payment method not appearing.

### ISSUE THREAD

**Issue by AidenistooOP** [Paymenter/Paymenter#157]
**Describe the bug**
The select payment option function on the demo website isnt working. See screenshot: https://predact.nl/aiden/Schermafbeelding%202023-10-03%20165608.png

**Expected behavior**
Shouldnt it show the payment methods?

**Comment by Valocai** [comment]
Not ment to on the demo sight.

- PickleCord

**Comment by Valocai** [comment]
> Add payment method in settings
> 
> Configure extensions that support payments and, if you need to, enable credits in the paymenter settings

I believe they where in about paymenter demo website. On the demo website I think corwin made the choice to not have a payment method.
