### ISSUE TITLE
Bug in paymenter credit add feature. [BUG] 

### ISSUE THREAD

**Issue by cloudrack-ca** [Paymenter/Paymenter#171]
Nothing big about bug just that if you simple take a look at 
![image](https://github.com/Paymenter/Paymenter/assets/145787423/926cc80b-b4f9-46fc-bd42-dd5d2ef8aeb4)
And then look at 

![image](https://github.com/Paymenter/Paymenter/assets/145787423/b7ead9a4-e5b0-4cf2-b639-d1edc020c97a)
you will see my slight confusion if i set it to 100 max and ive put 100 and its erroring out at 100 being the defaulted value the code that holds this should add +1 to the number the admin has set inside the panel to counteract this bug.

**Comment by Valocai** [comment]
Hiya! Try setting it to 101 and see if that works. If not wait for corwin to see this (:

PickleCord

**Comment by CorwinDev** [comment]
Its fixed in the command referenced :)

**Comment by cloudrack-ca** [comment]
Thank you thank you.
