### ISSUE TITLE
[BUG] Bug Found In UI Hindering 3rd Category viewable.

### ISSUE THREAD

**Issue by cloudrack-ca** [Paymenter/Paymenter#174]
If we look at the following image
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/145787423/276362058-aee70f3e-98b9-4f24-8821-a3480ec31ea1.png) we can see that the third category i have set known as `test` is not seen nor found do to the WELCOME BACK banner. ![image](https://github.com/Paymenter/Paymenter/assets/145787423/cee8a157-83d4-4f0b-855a-91103f2d1afe)

as stated as we can see i have three plans 2 valid one to test this theory which was correct
![image](https://github.com/Paymenter/Paymenter/assets/145787423/8c7c4a4e-d503-4b7d-aca0-854fae777831)
you can see three sets of categories and yes i have also made a test plan for the test category so it would display right the category as i already know if a category is Empty it will not provide results for that category when viewing store front end.

if you notice tho on mobile we can see test category no problem 
![image](https://github.com/Paymenter/Paymenter/assets/145787423/bb381dc5-e774-4130-84b6-7925bf9b8302)

**Comment by CorwinDev** [comment]
If a category hasn't any products its normal to not show the category

**Comment by cloudrack-ca** [comment]
Re-read my guy....

**Comment by zvikasdongre** [comment]
That's just a little css issue, should be fixable by adjusting the z-index of either the announcement or the dropdown.

**Comment by cloudrack-ca** [comment]
> That's just a little css issue, should be fixable by adjusting the z-index of either the announcement or the dropdown.

has todo with something along the layout of this banner 
![image](https://github.com/Paymenter/Paymenter/assets/145787423/f513d2d1-a011-4c04-9cc2-7b270d44703a)
 it hovers over things put it in back somehow behind nav
