### ISSUE TITLE
[BUG] UI Simple fix

### ISSUE THREAD

**Issue by cloudrack-ca** [Paymenter/Paymenter#175]
There seems to be a double URL inside the header navigation area. 
Nothing huge to fix just as you can see there is 2 invoice pages both link to same page.
![image](https://github.com/Paymenter/Paymenter/assets/145787423/d8349d8e-99eb-42c9-810c-4ef737881f8d)

**Comment by CorwinDev** [comment]
Already removed in 330702fcc637bf823331d3294936951346296737
