### ISSUE TITLE
after upgrade bug in externsions [BUG] 

### ISSUE THREAD

**Issue by cloudrack-ca** [Paymenter/Paymenter#186]
after upgrading paymenter and performing the manual upgrade the `/admin/extensions/browse` URL now contains no extensions 

![image](https://github.com/Paymenter/Paymenter/assets/145787423/dd252ad2-7a8c-45b9-8191-af0deab79dda)

**Comment by CorwinDev** [comment]
Should be fixed, can you recheck?
