### ISSUE TITLE
[BUG] Semi-annual price disappears in configurable options and in cart

### ISSUE THREAD

**Issue by ecocraft** [Paymenter/Paymenter#235]
**Describe the bug**
Semi-annual configurable option saves, but does not apply inside the cart and disappears from the editing menu.

**To Reproduce**
1. Go to Configurable options
2. Create an option
3. Set a semi-annual price
4. Save
5. Open the editing menu again
6. semi-annual price missing

**Expected behavior**
The semi-annual price should be applied to cart and be visible inside the menu.

**Screenshots**
![image](https://github.com/Paymenter/Paymenter/assets/51019518/9654c3ab-4acb-492d-bcd4-e2e292ed0a24)
Semi-annual price missing.
![image](https://github.com/Paymenter/Paymenter/assets/51019518/cf8033ae-24d8-4421-8c82-e100e1a27b33)
No price in cart.
![image](https://github.com/Paymenter/Paymenter/assets/51019518/ec69e650-d2a1-4381-bf10-ec4a95c99e2e)
All prices are stored correctly inside the DB.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Browser: Google Chrome
 - Version 119.0.6045.105 (64-bit)
 - Paymenter version: 0.8.2
 - Paymenter language: Czech (cs)

**Comment by ProgyNL** [comment]
its an wellknown issue it just doesnt display but when u enter it saves

**Comment by 09han09** [comment]
Does it show the semi annual price on the payment / checkout page (before you get redirected towards stripe, paypal or any other payment gateway)?

**Comment by ecocraft** [comment]
Well funny enough, it now shows in the cart and on the checkout page, but still not in the settings.

**Comment by 09han09** [comment]
Thank you for bringing this to our attention. There is already have a fix in place, and it will be included in the next update. If you find any more issues or have suggestions, please feel free to let us know. Your input helps us improve Paymenter.

Best wishes,
The Paymenter Team and Contributors
- Corwin in my dm's. (Not exactly what it said just figured to make it 'formal' because i am bored.)

**Comment by ecocraft** [comment]
This will be fixed in the next update.
