### ISSUE TITLE
[BUG] Cronjob date is not human readable

### ISSUE THREAD

**Issue by ItsLeon15** [Paymenter/Paymenter#263]
**Describe the bug**
The "Cronjob has not run in the last 8293 minutes." is not human readable.

**Expected behavior**
Could this be changed so it's something like "Cronjob has not run in the last 1 day, 5 hours and 23 minutes"?

**Screenshots**
![image](https://github.com/Paymenter/Paymenter/assets/64979109/417a69ef-42fc-4db9-8c7a-d00a59f2d8cc)

**Comment by gps949** [comment]
Additionally, the document does not seem to clearly specify the function of cronjobs (for example, what problems might arise if a cronjob is not executed for a long period). Furthermore, when deploying with Docker, it appears to be quite challenging to edit or add cronjobs within the container.

**Comment by CorwinDev** [comment]
I wouldn't really use docker (I'm not that experienced with docker so i can't help you with that :D)

**Comment by gps949** [comment]
> I wouldn't really use docker (I'm not that experienced with docker so i can't help you with that :D)

Haha, okay, although it would be much more convenient if Docker deployment were well-supported, no worries, I can consider carefully migrating to virtual machine deployment later.

**Comment by ItsLeon15** [comment]
> Additionally, the document does not seem to clearly specify the function of cronjobs (for example, what problems might arise if a cronjob is not executed for a long period). Furthermore, when deploying with Docker, it appears to be quite challenging to edit or add cronjobs within the container.

A list of what happens every cronjob could be added just to add more information, this could also go with your point with any problems as you could theoretically just take everything from the list as stuff that isn't happening every cron run. My main issue what that the minutes weren't being converted to a format such as `MM-dd'T'HH:mm:ss` so it would appear to something similar like `5 months, 6 days, 12 hours, 32 minutes, 10 seconds`. But if the original functionality of the page or if this has been fixed/not planned then this can be closed @CorwinDev.
