### ISSUE TITLE
[BUG] When using 100% off coupon invoice is still generated and requires it to be paid

### ISSUE THREAD

**Issue by NoPantsMcDance** [Paymenter/Paymenter#287]
**Describe the bug**
When using 100% off coupon invoice is still generated and requires it to be paid
Additionally the "invoice number" "due date" and "date of issue" is incorrect

**Expected behavior**
No invoice is generated and works the same as when the product cost is $0

**Screenshots**
![image](https://github.com/Paymenter/Paymenter/assets/1021611/52d5e715-99e2-4cff-aefd-8ee74775b9ba)
![image2](https://github.com/Paymenter/Paymenter/assets/1021611/02a46867-ebf8-42d3-be3e-50f4da606ca9)

**Comment by CorwinDev** [comment]
Fixed in f7b9f69
