### ISSUE TITLE
[BUG] Port Array doesn't work when use a location configurable option

### ISSUE THREAD

**Issue by NoPantsMcDance** [Paymenter/Paymenter#288]
**Describe the bug**
If you have a product that uses the port array while also using a configurable option for the location you get this error 

`[2023-12-07 23:39:16] production.ERROR: Pterodactyl: Error creating server: Undefined array key "data" on line 436 in file /var/www/paymenter/app/Extensions/Servers/Pterodactyl/Pterodactyl.php on line 436 in file /var/www/paymenter/app/Extensions/Servers/Pterodactyl/Pterodactyl.php  
`

**To Reproduce**
1. Create a product that uses a port array
2. Create a configurable option for location
3. Attempt to purchase and get above error
4. Complain about it on discord

**Expected behavior**
It works

**Screenshots**
![image](https://github.com/Paymenter/Paymenter/assets/1021611/75d1564e-2eb7-4a82-bb6d-f5be2a56fa9f)
![image](https://github.com/Paymenter/Paymenter/assets/1021611/b6a580f5-b6dd-438e-8295-cbdc44d5c1d9)

NOTE: I have tested and if you remove the config option the server creates as expected. This affects ALL products that use the location config option shown in the screenshots.

**Comment by CorwinDev** [comment]
Fixed in latest commit
