### ISSUE TITLE
[BUG] Admin area side navigation ticket statuses list has overlapping items

### ISSUE THREAD

**Issue by mendozal** [Paymenter/Paymenter#314]
In the admin area side navigation section, the card showing ticket counts  (all, closed, open) has text overlapping the next element.

If I zoom out the browser to 90% it shows the items nicely aligned for English.
But for Spanish I need to get the browser down to 80% zoom in order for the items to show correctly, because the text is longer.

On the other hand if I get the browser to 110%, the items wrap nicely.

Is it possible to have the card elements wrap sooner?

![screenshot](https://github.com/Paymenter/Paymenter/assets/4621970/dc56c8fa-eea9-47f2-bbfd-2b4d97c230b3)
![spanish](https://github.com/Paymenter/Paymenter/assets/4621970/0d6a94d9-a608-4635-898d-8ff8c6c985fd)
![screenshot2](https://github.com/Paymenter/Paymenter/assets/4621970/97767d77-bfc8-42c3-bdd6-d7e1f6b49e79)

**Comment by CorwinDev** [comment]
There you go

Stable release coming 🔜
