### ISSUE TITLE
[BUG] Issues with One-Time Billing Product

### ISSUE THREAD

**Issue by gps949** [Paymenter/Paymenter#363]
**Describe the bug**
I start the Paymenter with docker.
When setting a product's billing type to "one-time," the price changes to "free" upon adding the product to the cart, despite the product page showing the correct price. Additionally, configuring a product with a $0 monthly fee and a setup fee results in a 500 error during the checkout process.

**To Reproduce**

1. Go to the product page and set the billing type to "one-time."
2. Add the product to the cart. Notice the price changes to "free."
3. Go back and set the product with a $0 monthly fee and an additional setup fee.
4. Add the product to the cart and proceed to checkout.
5. Encounter a 500 error.

**Expected behavior**
The expected behavior for the first scenario is that the product retains its one-time price when added to the cart. For the second scenario, the checkout process should complete without errors, respecting the $0 monthly fee and the setup fee configuration.

**Screenshots**
<img width="1525" alt="Screenshot 2024-02-03 at 10 19 45 AM" src="https://github.com/Paymenter/Paymenter/assets/7601383/65793ea7-bc01-4947-b0fe-c7bf622078d1">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser:  safari
 - Version 17.4

**Additional context**
The backend log error for the 500 issue is as follows:
```
[previous exception] [object] (ErrorException(code: 0): Undefined variable $quantity at /tmp/paymenter/framework/views/eb67f7707feb5c4426b122e9794243d2.php:268)
```

**Comment by CorwinDev** [comment]
Fixed in v0.9.2
