### ISSUE TITLE
[BUG]  Active Products with an Open Invoice cannot be Cannceled

### ISSUE THREAD

**Issue by Tix-Hosting** [Paymenter/Paymenter#404]
**Describe the bug**
A Product which is already existing and has a Invoice for Renewal cannot be Cancelled. 

**To Reproduce**
1. Order a Product
2. Wait For Renewal Phase
3. See Missing Cancel Button (Screenshot)
4. 
**Expected behavior**
The Customer Should be Able to Cancel the Product (both at the End of Runtime and Immediately) and the Invoice should also be Deleted as soon as he Cancelles the Product

**Screenshots**
![Bild_2024-03-26_212545391](https://github.com/Paymenter/Paymenter/assets/91834610/e13dc4f4-814d-48cc-ae0f-3f79f24aa425)

**Desktop (please complete the following information):**
- v0.9.3

**Comment by CorwinDev** [comment]
Hi, 
Those issues/enhancements will not get added in the current versions but will be included in our next major version (v1, in the works)
