### ISSUE TITLE
[BUG] If a Product gets Ordered "on Mistake" the Status will stay on Pending 

### ISSUE THREAD

**Issue by Tix-Hosting** [Paymenter/Paymenter#405]
**Describe the bug**
Similiar to Issue Report #404 if the Client chooses a Product but does not Pay the Product then the Product will stay in his Customer Area.. 

**To Reproduce**
1. Buy a Product
2. Click on Go To Checkout
3. Click on Checkout
4. Cancel the Paypal / Gateway Process
5. Product will be on the Customer Area (which is fine, because maybe the Customer used a Method which needs time)
6.  The User Should have the Option to Cancel the Order so his Customer Area is not Cluttered. That is currently not the Case

**Expected behavior**
As the Product will only get Created if the Customer Pays the Invoice, there is no need to "Enforce" the Purchase and the Users notice this to as they get no service until they pay... ´

Therefore there should be a Button both on the Product aswell on the Invoice "Cancel Order" which immediatly deletes the Invoice and removes the Product from the Customer Area...

**Desktop (please complete the following information):**
- v.0.9.3

**Comment by CorwinDev** [comment]
Hi, 
Those issues/enhancements will not get added in the current versions but will be included in our next major version (v1, in the works)
