### ISSUE TITLE
[BUG] Immediate Cancellation does not Cancel Immediatly

### ISSUE THREAD

**Issue by Tix-Hosting** [Paymenter/Paymenter#406]
**Describe the bug**
If the User chooses to cancel his Product Immeadiatly and clicks on cancel, then the Service gets instantly removed from Proxmox, Pterodactyl, Hetzner and so on... So far so good! 

BUT 

The Product stays in the Customer Area. I already asked for Support in Discord and there the answer was given, that that is normal Behaivior and the Product gets deleted out of the Customer Area 24 Hours after Clicking the Cancel button.. I will check back in a Few Hours as comment here, if it is gone out of the Customer Area 24 Hours after, but in any case, if the User clicks on Cancel Immediate, and the Product gets Canceled Immedatly out of the Extension, then it should also be removed out of the Customer Area

**To Reproduce**
1. Click on a Existing Product
2. Click on Cancel Product
3. Select Immediate as Cancel Option
4. Click on Cancel
5. See the Problem

**Expected behavior**
The Product should be deletet Emmediatly out of the Customer Area, as the Feature suggests it does.. And the Extension Product gets deleted As Soon as the User clicks on the Cancel Button, so it would only make sense to delete it Directly out of the Customer Area

**Screenshots**
![Bild_2024-03-26_214553592](https://github.com/Paymenter/Paymenter/assets/91834610/585cfb4f-d14c-4042-84e4-7ad3825430f9)

**Desktop (please complete the following information):**
- v0.9.3

**Comment by Tix-Hosting** [comment]
UPDATE: Even after the 24 Hours it does not delete out of the Customer Area

**Comment by PhillipEis** [comment]
I have same problem.

**Comment by stevebrainng** [comment]
Hi, @CorwinDev could you please assign this to me?
