### ISSUE TITLE
[BUG] Error 500 When reordering products

### ISSUE THREAD

**Issue by XceptDev** [Paymenter/Paymenter#411]
When trying to reorder products, 500 SERVER ERROR

**To Reproduce**
1. Go to /admin/products
2. Click "Reorder" on some category
3. Reorder something
4. Click save
5. Error

**Screenshots**
![image](https://github.com/Paymenter/Paymenter/assets/77639981/9fa75f6e-d0c4-496e-a77b-401c204cbfc7)
![image](https://github.com/Paymenter/Paymenter/assets/77639981/9207971d-694a-4322-8169-57710754c077)

**Additional context**
Paymenter version: Latest stable

**Comment by imJuff** [comment]
I'm also getting 500 Server Error when clicking save after reordering products.

**Comment by purejosh** [comment]
Rearranging the categories also doesn't work. It says it updates, but the categories aren't actually changing on the page. So, both ordering products and categories is busted.
