### ISSUE TITLE
[BUG] Image not save

### ISSUE THREAD

**Issue by piratetm** [Paymenter/Paymenter#426]
**Describe the bug**
Pictures are not saved when redeployed because are stored in local storage. This is more noticeable when working with distributed systems. It is considered good practice to store them in a Database.

**To Reproduce**
1. Go to 'Add image'
2. Redeploy server
4. Failed to load resource: the server responded with a status of 404 ()
5.

**Expected behavior**
For example, WordPress stores all its images in a database.

**Screenshots**
 ![image](https://github.com/Paymenter/Paymenter/assets/40763772/b1e14946-744c-4b43-8268-f4f7cb0e4125)

**Server (please complete the following information):**
- k8s
- deployment

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser Chrome

**Comment by CorwinDev** [comment]
Did you link the storage? `php artisan storage:link`

**Comment by piratetm** [comment]
> Did you link the storage? `php artisan storage:link`

Yes. But it is a bad practice to use local storage. As I said, when working with distributed systems, this is the weak link. How I can change to database storage?

![image](https://github.com/Paymenter/Paymenter/assets/40763772/f8ad37fe-6aaa-46ff-9fb2-76921296abb4)

**Comment by CorwinDev** [comment]
You can't and shouldn't store files in a database.
You could change the storage type to either [AWS S3](https://laravel.com/docs/11.x/filesystem#s3-driver-configuration) compatible storage or [SFTP](https://laravel.com/docs/11.x/filesystem#sftp-driver-configuration) or you could use any other supported storage driver

**Comment by piratetm** [comment]
Will he have enough environment variables to switch to s3?

**Comment by piratetm** [comment]
I did everything as indicated in the official documentation. Does not work. When loading an image in logo - it does not go to s3..

1. Run docker with `        command: ['sh', '-c', 'printenv | grep "^PAYMENTER_" | sed "s/^PAYMENTER_//g" > /var/www/paymenter/.env && /usr/bin/supervisord --configuration=/etc/supervisord.conf']`
2. Runed `composer require league/flysystem-aws-s3-v3 "^3.0" --with-all-dependencies`
3. Nothing, no errors/warnings in log and debug console


![image](https://github.com/Paymenter/Paymenter/assets/40763772/4448b035-2f80-4f7c-bc86-68774708c8e3)
