### ISSUE TITLE
[BUG] Email link

### ISSUE THREAD

**Issue by Bansku-Dansku** [Paymenter/Paymenter#427]
**Describe the bug**
When recieving the email about a new ticket the button redirects to the localhost one.

**To Reproduce**
1. Go to 'Customer Area'
2. Click on 'Tickets'
3. Click on '+ Create'
4. Add the necessary info.
5. Click on 'Create'
6. Go to your email
7. Select the one about the new ticket
8. Press on the button to view the ticket.
9. It redirects to localhost/tickets/ticket_id

**Expected behavior**
The button would redirect to the ticket and not to the localhost. (Example: billing.paymenter.org/tickets/112)

**Screenshots**
![image](https://github.com/Paymenter/Paymenter/assets/110292588/183a0c85-0fff-4b8f-90cd-78c2f320ece4)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Crhome
 - Version 0.9.3

**Comment by CorwinDev** [comment]
Thanks for the issue, luckily this is a small configuration issue:
- Open up your .env file (normally located in /var/www/paymenter).
- Change APP_URL to your url with https (eg https://billing.paymenter.org)

*I recommend joining our discord so we can easily help you with those issues!*
