### ISSUE TITLE
Mobile Version Bad UI + Cart is Missing [BUG] 

### ISSUE THREAD

**Issue by QuikBolte** [Paymenter/Paymenter#43]
**Describe the bug**
1. On Mobile Version Menu is in center right next to Paymenter Logo, please check photo.
![IMG_20221111_195252](https://user-images.githubusercontent.com/75838590/201365378-17f2b778-b229-4eb7-baf9-ec554677ba2f.jpg)

2. Categories are on left side of screen instead of in middle with more width. Please check photo.
![Screenshot_2022-11-11-19-53-47-472-edit_com android chrome](https://user-images.githubusercontent.com/75838590/201365659-f0f3609e-bfff-4429-9f87-ca581c0ec20f.jpg)

3. There is no cart shown on Mobile View making it impossible for us to order. Please check photo.
![Screenshot_2022-11-11-19-55-58-087-edit_com android chrome](https://user-images.githubusercontent.com/75838590/201365998-77fb75c7-8e2b-408a-853a-2803c94864f4.jpg)

4. Overall UI looks bad on Mobile View.

**To Reproduce**
1. Fix menu by placing it on top right of the screen.
2. Fix categories by changing their position from left to middle and increasing their width to make them look better.
3. Fix cart by adding it on Mobile View.
4. Fix overall UI by making it look better. Also everything is not shown on Mobile UI :), Tickets also doesn't show and anything else Paymenter has.

**System Info (please complete the following information):**
 - OS: Android 12
 - Browser: Chrome
 - Version: 107

**Comment by CorwinDev** [comment]
Will be added to our todo list!

**Comment by QuikBolte** [comment]
Thanks! Also everything is not shown on Mobile UI :), Tickets also doesn't show and anything else Paymenter has.

**Comment by CorwinDev** [comment]
Everything is solved except for the cart
