### ISSUE TITLE
[BUG] Error Virtfusion Creating VPS

### ISSUE THREAD

**Issue by TheVisual** [Paymenter/Paymenter#440]
**Describe the bug**
Error Virtfusion Creating VPS

**To Reproduce**
1. Add credits to user
2. Buy plan with credits 
3. See error never gets setup

**Expected behavior**
Create user acc + VPS

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Additional context**
Logs: https://logs.paymenter.org/log/TD7v1tCn8t/38ZtdkIzyr.txt

**Comment by CorwinDev** [comment]
It seems that your user is already existing, be sure to set the `External Relational Identifier` on Virtfusion to your ID on Paymenter!

**Comment by TheVisual** [comment]
> It seems that your user is already existing, be sure to set the `External Relational Identifier` on Virtfusion to your ID on Paymenter!

Alright thank you!
