### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Wisnoe26** [Paymenter/Paymenter#449]
The range port does not work in the pterodactyl panel. Or please add automatic port allocation like pterobill hehe 
![Screenshot_2024-06-06-00-16-50-995_com android chrome](https://github.com/Paymenter/Paymenter/assets/140087177/1c6be98d-8be0-4193-be6a-e2efd5eb42b3)
![Screenshot_2024-06-06-00-17-14-446_com android chrome-edit](https://github.com/Paymenter/Paymenter/assets/140087177/d9d67340-d41e-46fc-aa49-7529bea6f359)

**Comment by CorwinDev** [comment]
Check https://paymenter.org/features/pterodactyl/ port array, should do the same as pterobill
