### ISSUE TITLE
[BUG] Coupon applied to a different package at checkout fails to provide discount, allows free checkout, and creates backend orders not shown on frontend.

### ISSUE THREAD

**Issue by AgoMC** [Paymenter/Paymenter#453]
If you create a coupon and select a package to use it on, and then you go to the checkout with another package, and use the coupon, it uses it but there's no discount. But you can also check out with it and once you confirm the payment type, it goes for free and creates an order on the backend but not the frontend. So it basically does nothing but create ghost orders 

**Expected behavior**
Either says you can't use this coupon for this specific product, or go through with the order and no discount (and not ghosted)

**Desktop (please complete the following information):**
Ubuntu 22.04

**Comment by zvikasdongre** [comment]
Can confirm it creates ghost orders.
(dumped the $services variable for clarity)
![image](https://github.com/Paymenter/Paymenter/assets/47200577/feffc6a2-28ec-48f2-91a4-bbeeed180cef)
![image](https://github.com/Paymenter/Paymenter/assets/47200577/4988cea9-d492-48e3-8bcc-60d5b74cdd48)
