### ISSUE TITLE
[BUG] When creating a pterodactyl server

### ISSUE THREAD

**Issue by clanddora** [Paymenter/Paymenter#455]
When we buy the server, the payment is confirmed and it is written that the service is active, but after the server is not issued in pterodactyl and an error appears in the logs from below on the screenshot. At the same time, if you then click the create button directly into the services, it will create without any problems. Please help me.

![image](https://github.com/Paymenter/Paymenter/assets/171748854/db351465-e3c8-4f89-bbb7-f9ccf75d6264)

full eror: https://logs.paymenter.org/log/i5ZXqLzAhY/XwKGqxau60.txt

**Comment by CorwinDev** [comment]
Try `cd /var/www/paymenter && php artisan queue:restart`
