### ISSUE TITLE
[BUG] php artisan p:upgrade --url https://api.paymenter.org/beta Failed on latest BETA build

### ISSUE THREAD

**Issue by TheVisual** [Paymenter/Paymenter#456]
**Describe the bug**
php artisan p:upgrade --url https://api.paymenter.org/beta Failed on latest BETA build (Won't update just keep notification)

**To Reproduce**
php artisan p:upgrade --url https://api.paymenter.org/beta

**Expected behavior**
Update

**Comment by CorwinDev** [comment]
Fixed
