### ISSUE TITLE
[FEATURE] Monitoring add to Paymenter 

### ISSUE THREAD

**Issue by nvdmedianl** [Paymenter/Paymenter#47]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

monitoring services with ping or something else or whether they are online as is also built into whmcs

**Describe alternatives you've considered**

there are nice services available but I would still like to see that it is in paymenter as a function

**Comment by Marijn-de-Mul** [comment]
This would be very cool. Maybe there is a possibility to work with some kind of API for this like UptimeRobot, BetterUptime or another monitoring service. This would remove the need for a separate status page.

**Comment by BasToTheMax** [comment]
Also a server monitor that monitors the physical servers ram/cpu/disk usage. Hetrixtools has something like this

**Comment by ItsLeon15** [comment]
WIP
