### ISSUE TITLE
[BUG] Items in cart can't be removed due to IDs

### ISSUE THREAD

**Issue by AgoMC** [Paymenter/Paymenter#471]
This is very confusing, but when you add a product to your cart, it uses a cart ID. So adding in any service counts from 0, 1, 2, 3, etc. But when you're removing an item in the cart, it uses the service ID instead for some reason. So if I have 3 items in my cart:

- Cart ID: 0, Product ID: 1
- Cart ID: 1, Product ID: 3
- Cart ID: 2, Product ID: 2

If I click to remove the 1st item, it removes the second item in the cart, as it's being removed using the Product ID, not the cart ID.
You can see this in the Index.php in the Checkout folder:

`    public function removeProduct($key)
    {
        $cart = session()->get('cart');
        unset($cart[$key]);
        session()->put('cart', $cart);
        $this->updateCart();
    }`

And to remove it on the frontend:

`wire:click="removeProduct({{ $product->id }})"`

This in all is just a dumb way of doing it, and I can't seem to create a new `cartID` variable and use it that way.

Instead of using the Service ID and Cart ID, it should just be one way. I think the Cart ID is smarter, as you may have multiple of the same service, but with a different configuration (which in turn would have 2 items in the cart being the same ID). Using the Cart ID would be able to have any amount of services, and when you remove one, it just reorders the items in it from 0 again. So if you have 5 items, cart IDs; 0, 1, 2, 3, 4. And you remove Cart ID 2, it would reorder to; 0, 1, 2, 3.

**Comment by CorwinDev** [comment]
You sure you don't use a old version or a custom theme? 

https://github.com/Paymenter/Paymenter/blob/5b38bcd150ae04cc787e6bae81f5701a56ee4377/themes/default/views/livewire/checkout/index.blade.php#L64 here it's already key

**Comment by AgoMC** [comment]
I'm using a custom theme I made on the most recent version.

That's so weird tho

**Comment by AgoMC** [comment]
I used the command to create a new theme, so maybe it's not updated. Just had to change the @foreach statement above to:
`@foreach ($this->products as $key => $product)`

Before it was: `@foreach ($this->products as $product)`

All good now, thank you :D

**Comment by TheVisual** [comment]
> I used the command to create a new theme, so maybe it's not updated. Just had to change the @foreach statement above to: `@foreach ($this->products as $key => $product)`
> 
> Before it was: `@foreach ($this->products as $product)`
> 
> All good now, thank you :D

please close issue if fixed  🙏
