### ISSUE TITLE
[BUG] Virtfusion Extension Dosen't Give 1 IP By Default

### ISSUE THREAD

**Issue by VendorAttestation** [Paymenter/Paymenter#495]
**Describe the bug**
Virtfusion Extension Dosen't Give 1 IP By Default

**To Reproduce**
Update The Plugin and try to buy

**Expected behavior**
Give 1 IP

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
(https://github.com/Paymenter/Paymenter/commit/3bbc6a6e05c23d7e071573d6ca5afc45a44e6a56)

I think it should give 1 IP by default (As its useless without 1 IP) not the workaround about making configurable options which not everyone does as i don't sell stuff like that so i was forced to revert the plugin

**Comment by CorwinDev** [comment]
I've reverted that change, please update your extension to 1.2.1

Thanks for reporting :)
