### ISSUE TITLE
Migrate from WHMCS

### ISSUE THREAD

**Issue by JamCh01** [Paymenter/Paymenter#553]
Hello Paymenter Developers,

I'm trying to migrate from WHMCS to Paymenter. I found there were some commits about this func (#52 , #51  ), but I cannot find files in my newly installed Paymenter.

Has this feature been removed? Can you provide any suggestions or methods for migrating?

Thanks!

**Comment by CorwinDev** [comment]
We never had a fully functional WHMCS migrator. We also do not have any plans for a migrator at this moment

**Comment by luanfalle** [comment]
I believe this should be reconsidered. Without a migration tool, companies with large client bases won't be willing to adopt Paymenter due to the manual effort (and cost) required.
