### ISSUE TITLE
[FEATURE] CyberPanel Extension

### ISSUE THREAD

**Issue by KeizerWilmer** [Paymenter/Paymenter#66]
**Is your feature request related to a problem? Please describe.**
I would like to use the open source CyberPanel, instead of the paid DirectAdmin.

**Describe the solution you'd like**
Add CyberPanel to the extensions.

**Describe alternatives you've considered**
DirectAdmin is available. But you have to pay for DirectAdmin, and it's not open source.

**Additional context**
For information about CyberPanel's API, visit: [https://cyberpanel.docs.apiary.io/](https://cyberpanel.docs.apiary.io/)

**Comment by CorwinDev** [comment]
Moved to https://github.com/Paymenter/Extensions/issues/1

**Comment by fernandobayit** [comment]
+1
