### ISSUE TITLE
[BUG] 500 server error on checkout

### ISSUE THREAD

**Issue by P0werGam3r** [Paymenter/Paymenter#73]
**Describe the bug**
I installed the panel correctly by following the docs. I put my pterodactyl information in the extention without any error. then I created a free product to test it but when I clicked on checkout it gave an 500 server error without futher information.

**To Reproduce**
1. make a free product
2. put it in your cart
3. press "checkout"
4. 500 | server error

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Comment by CorwinDev** [comment]
Hi, 

Could you post your error logs? You can do that by running the command: Please use `/var/www/paymenter/storage/logs/laravel-$(date +%F).log | nc log.paymenter.org 99`

**Comment by P0werGam3r** [comment]
/var/www/paymenter/storage/logs/laravel-2023-02-07.log: line 1: syntax error near unexpected token `('
/var/www/paymenter/storage/logs/laravel-2023-02-07.log: line 1: `[2023-02-07 20:16:59] local.ERROR: Symfony\Component\Mailer\Transport\Dsn::__construct(): Argument #2 ($host) must be of type string, null given, called in /var/www/paymenter/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 174 {"userId":1,"exception":"[object] (TypeError(code: 0): Symfony\\Component\\Mailer\\Transport\\Dsn::__construct(): Argument #2 ($host) must be of type string, null given, called in /var/www/paymenter/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php on line 174 at /var/www/paymenter/vendor/symfony/mailer/Transport/Dsn.php:28)'


It doesn't upload it to log.paymenter.org

**Comment by CorwinDev** [comment]
Alright, you should setup your mail server at the admin side

**Comment by P0werGam3r** [comment]
Oke, thanks for respoding this fast 👍
