### ISSUE TITLE
[BUG] Frontpage Markdown/HTML text is buggy.

### ISSUE THREAD

**Issue by infectedw** [Paymenter/Paymenter#87]
**Describe the bug**
The issue relates to the front page text, when you attempt to use HTML language, markdown simply disables itself, allowing you to only use HTML or markdown. HTML is buggy, as is markdown. You are unable to center text, "h1" sometimes works, but sometimes does not, "a" is pretty buggy when it comes to links, and even "img" does not want to work. (Occasionally, it displays some strange symbols at the end of the link)

**To Reproduce**
1. Write a text
2. Add ** before the first word and ** after the last word text will bold itself
3. Then add <center> at the start and </center> at the end, markdown will just disable itself and show ** at the start and end not allowing text to be bold. 

**Expected behavior**
I expect it to be bold at the end and start of the text, and I expect it to be centered.

**Screenshots**
https://i.imgur.com/EQAEiUN.png - This screenshot show text with HTML Tag <center></center>
https://i.imgur.com/AIxwKvI.png - This screenshot is what happens when I just add ** for text bolding

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox, Chrome,  OperaGX
 - Version 111.0, 111.0, LVL4 (core: 96.0.4693.127)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10+
 - OS: Android 12, OneUI 4.1
 - Browser Firefox, OperaGX
 - Version 111.1.1, 1.9.4

**Additional context**
There is no additional context.

**Comment by CorwinDev** [comment]
You can't use markdown inside html

Markdown which works:

**test**


Markdown inside html

<div>
**test**
</div>
