### ISSUE TITLE
[BUG] Long package name causes a newline split mid word

### ISSUE THREAD

**Issue by ecocraft** [Paymenter/Paymenter#88]
**Description**
When you have a longer name than space for it, the name will split in the middle of a word.

**To Reproduce**
1. Create a product
2. Enter a long name (e.g. Paper Minecraft Server Zdarma)
3. Save it
4. Open the store's main page
5. See the split mid-word

**Expected behavior**
The name should split not in the middle of a word but should replace a space with a new line.

**Screenshots**
![chrome_q4KWQUCVaS](https://user-images.githubusercontent.com/51019518/229304708-05b6c3d9-11a8-4e25-9fe0-bc1842609b4a.png)
![chrome_dqUYuDJpsJ](https://user-images.githubusercontent.com/51019518/229304710-3f08a4fc-4846-4645-a813-55eff4d2a89b.png)

**Desktop:**
 - OS: Windows 10 22H2
 - Browser: Google Chrome
 - Version 111.0.5563.147 (64-bit)

**Comment by CorwinDev** [comment]
Fixed in latest commit(release at 0.5)
