### ISSUE TITLE
Response 500 Error in first page

### ISSUE THREAD

**Issue by carlosMartin0213** [Paymenter/Paymenter#89]
**Describe the bug**
The homepage returns 500 error.
I followed these steps for running the server.
1. Cloned the repository.
"git clone https://github.com/Paymenter/Paymenter.git"
2. Update dependencies
"composer install"
3.Run the server
"php artisan serve"

When I connect to "localhost:8000", server response 500 error.

How can I solve this problem?

Thanks.

**Comment by CorwinDev** [comment]
Hi,

Did you run `php artisan migrate`?

https://paymenter.org/docs/category/installation

**Comment by carlosMartin0213** [comment]
Already done.
I solved this problems after run "npm install" command.
After that it is working.
