### ISSUE TITLE
[BUG] Forgot Password

### ISSUE THREAD

**Issue by Almahost** [Paymenter/Paymenter#95]
**Describe the bug**
Forgot Password (if ReCaptcha 3 is active, it shows error 500)

**Comment by CorwinDev** [comment]
Hi,

Can you check if you've setted up email settings?
And please check your logs for the error! (you can do this be running the command: `tail -n 100 /var/www/paymenter/storage/logs/laravel-$(date +%F).log | nc log.paymenter.org 99`)
