### ISSUE TITLE
[BUG] Setup fee does not work

### ISSUE THREAD

**Issue by BasToTheMax** [Paymenter/Paymenter#97]
**Describe the bug**
When setting a setup fee it should be on the checkout page and should also be counted when paying

**To Reproduce**
1. Setup paymenter
2. Setup a payment method (stripe in my case)
3. Setup a product with a setup fee
4. Login as a client, click on a product.
5. On the checkout page, the setup fee does not show

**Expected behavior**
The setup fee should show and should also get counted on the price

**Screenshots**
![image](https://user-images.githubusercontent.com/55401336/232328515-bab1772c-e51a-4cdd-b9e3-4998ce99bbe4.png)
![image](https://user-images.githubusercontent.com/55401336/232328529-8018910e-cb92-47be-917c-c1cbc7c5d9f8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu desktop 20.04 LTS
 - Browser: chrome

**Additional context**
*none*

**Comment by CorwinDev** [comment]
Fixed, release in 0.6
